# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 743b674a114faecf909bee3bb4de2cfaa11def2ef48adf57422576a61a80d2d1333930e46bd5a3bcb35af0a6444d854c635bb3f4ac33e86ad1050c47dd01476b

test:
  secret_key_base: d0f3897612e22325ddc9006d544ed9b6fe63d16c03e6cde3b08dc0ae93064ea6c581c0ac06766a0074e5abb70f5b75fe064d8d698b4350e553e3234d6758d128

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
